=== saidulIslam1602/MaritimeIQ_Platform/deployment/azure/schemas/arm-template-slim.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Simplified ARM template schema",
  "description": "Lightweight schema to unblock local validation when resource provider definitions are unavailable offline.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "Schema reference for the deployment template."
    },
    "contentVersion": {
      "type": "string",
      "description": "Template content version."
    },
    "parameters": {
      "type": "object",
      "description": "Template parameters object.",
      "additionalProperties": true
    },
    "variables": {
      "type": "object",
      "description": "Template variables object.",
      "additionalProperties": true
    },
    "functions": {
      "type": "array",
      "description": "User-defined template functions.",
      "items": {
        "type": "object"
      }
    },
    "resources": {
      "type": "array",
      "description": "Resource definitions.",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "description": "Resource type identifier (e.g., Microsoft.Storage/storageAccounts)."
          },
          "apiVersion": {
            "type": "string",
            "description": "Resource API version."
          },
          "name": {
            "type": "string",
            "description": "Resource name."
          },
          "location": {
            "type": [
              "string",
              "null"
            ],
            "description": "Resource location (may be omitted for global resources)."
          },
          "tags": {
            "type": "object",
            "additionalProperties": true
          },
          "dependsOn": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "properties": {
            "type": [
              "object",
              "array",
              "string",
              "number",
              "boolean",
              "null"
            ],
            "additionalProperties": true
          },
          "sku": {
            "type": "object",
            "additionalProperties": true
          },
          "resources": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": true
            }
          }
        },
        "required": [
          "type",
          "apiVersion",
          "name"
        ],
        "additionalProperties": true
      }
    },
    "outputs": {
      "type": "object",
      "description": "Template outputs object.",
      "additionalProperties": true
    }
  },
  "required": [
    "resources"
  ],
  "additionalProperties": true
}

=== saidulIslam1602/MaritimeIQ_Platform/publish/deployment/data-factory/data-factory-complete.json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "dataFactoryName": {
      "type": "string",
      "defaultValue": "maritimeiq-data-factory",
      "metadata": {
        "description": "Name of the Data Factory"
      }
    },
    "location": {
      "type": "string",
      "defaultValue": "norwayeast",
      "metadata": {
        "description": "Location for all resources"
      }
    },
    "eventHubNamespace": {
      "type": "string",
      "defaultValue": "ehns-maritimeplat-70396"
    },
    "sqlServerName": {
      "type": "string",
      "defaultValue": "sql-maritimeplat-70396"
    },
    "sqlDatabaseName": {
      "type": "string",
      "defaultValue": "maritimeplat-db"
    },
    "storageAccountName": {
      "type": "string",
      "defaultValue": "stmaritimeplat70396"
    },
    "keyVaultName": {
      "type": "string",
      "defaultValue": "kv-maritimeplat-70396"
    }
  },
  "variables": {
    "eventHubConnectionString": "[listKeys(resourceId('Microsoft.EventHub/namespaces/authorizationRules', parameters('eventHubNamespace'), 'RootManageSharedAccessKey'), '2021-11-01').primaryConnectionString]",
    "storageConnectionString": "[concat('DefaultEndpointsProtocol=https;AccountName=', parameters('storageAccountName'), ';AccountKey=', listKeys(resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccountName')), '2021-09-01').keys[0].value, ';EndpointSuffix=core.windows.net')]"
  },
  "resources": [
    {
      "type": "Microsoft.DataFactory/factories",
      "apiVersion": "2018-06-01",
      "name": "[parameters('dataFactoryName')]",
      "location": "[parameters('location')]",
      "identity": {
        "type": "SystemAssigned"
      },
      "properties": {}
    },
    {
      "type": "Microsoft.DataFactory/factories/linkedServices",
      "apiVersion": "2018-06-01",
      "name": "[concat(parameters('dataFactoryName'), '/aisdataeventhub')]",
      "dependsOn": [
        "[resourceId('Microsoft.DataFactory/factories', parameters('dataFactoryName'))]"
      ],
      "properties": {
        "type": "AzureEventHub",
        "typeProperties": {
          "connectionString": "[variables('eventHubConnectionString')]"
        }
      }
    },
    {
      "type": "Microsoft.DataFactory/factories/linkedServices",
      "apiVersion": "2018-06-01",
      "name": "[concat(parameters('dataFactoryName'), '/maritimesqldb')]",
      "dependsOn": [
        "[resourceId('Microsoft.DataFactory/factories', parameters('dataFactoryName'))]"
      ],
      "properties": {
        "type": "AzureSqlDatabase",
        "typeProperties": {
          "server": "[concat(parameters('sqlServerName'), '.database.windows.net')]",
          "database": "[parameters('sqlDatabaseName')]",
          "authenticationType": "ManagedServiceIdentity"
        }
      }
    },
    {
      "type": "Microsoft.DataFactory/factories/linkedServices",
      "apiVersion": "2018-06-01",
      "name": "[concat(parameters('dataFactoryName'), '/maritimestorage')]",
      "dependsOn": [
        "[resourceId('Microsoft.DataFactory/factories', parameters('dataFactoryName'))]"
      ],
      "properties": {
        "type": "AzureBlobStorage",
        "typeProperties": {
          "connectionString": "[variables('storageConnectionString')]"
        }
      }
    },
    {
      "type": "Microsoft.DataFactory/factories/linkedServices",
      "apiVersion": "2018-06-01",
      "name": "[concat(parameters('dataFactoryName'), '/maritimekeyvault')]",
      "dependsOn": [
        "[resourceId('Microsoft.DataFactory/factories', parameters('dataFactoryName'))]"
      ],
      "properties": {
        "type": "AzureKeyVault",
        "typeProperties": {
          "baseUrl": "[concat('https://', parameters('keyVaultName'), '.vault.azure.net/')]"
        }
      }
    }
  ],
  "outputs": {
    "dataFactoryName": {
      "type": "string",
      "value": "[parameters('dataFactoryName')]"
    },
    "dataFactoryId": {
      "type": "string",
      "value": "[resourceId('Microsoft.DataFactory/factories', parameters('dataFactoryName'))]"
    },
    "dataFactoryIdentityPrincipalId": {
      "type": "string",
      "value": "[reference(resourceId('Microsoft.DataFactory/factories', parameters('dataFactoryName')), '2018-06-01', 'Full').identity.principalId]"
    },
    "studioUrl": {
      "type": "string",
      "value": "[concat('https://adf.azure.com/en-us/home?factory=/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.DataFactory/factories/', parameters('dataFactoryName'))]"
    }
  }
}
